name: alpine-docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  alpine-docker:
    name: Docker build based on alpine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        withtests: [0, 1]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Docker build
        working-directory: ${{github.workspace}}
        run: docker build --build-arg TEST=${{matrix.withtests}} -t coincenter .
