name: docker-publish

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sjanel/coincenter:latest

      - name: Tag current version
        run: |
          VERSION=`docker run sjanel/coincenter --version | head -1 | cut -d' ' -f 3`
          NEW_TAG="sjanel/coincenter:${VERSION}"
          docker tag sjanel/coincenter:latest $NEW_TAG
          docker push $NEW_TAG
