name: docker-publish

on:
  push:
    branches:
      - main

jobs:
  docker-publish:
    name: Publish Docker image to public Docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: sjanel/coincenter:latest

      - name: Build and push alpine
        uses: docker/build-push-action@v5
        with:
          file: alpine.Dockerfile
          context: .
          push: true
          tags: sjanel/coincenter:alpine

      - name: Tag current ubuntu version (if release one)
        run: |
          VERSION=`docker run sjanel/coincenter:latest --version | head -1 | cut -d' ' -f 3`
          case $VERSION in *.*.*.*) exit 0;; esac
          NEW_TAG="sjanel/coincenter:${VERSION}"
          docker tag sjanel/coincenter:latest ${NEW_TAG}
          docker push ${NEW_TAG}

      - name: Tag current alpine version (if release one)
        run: |
          VERSION=`docker run sjanel/coincenter:alpine --version | head -1 | cut -d' ' -f 3`
          case $VERSION in *.*.*.*) exit 0;; esac
          NEW_TAG="sjanel/coincenter:${VERSION}-alpine"
          docker tag sjanel/coincenter:alpine ${NEW_TAG}
          docker push ${NEW_TAG}
