name: docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        with-tests: [0, 1]
        file-name: ["Dockerfile", "alpine.Dockerfile"]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Docker build
        working-directory: ${{github.workspace}}
        run: docker build --build-arg BUILD_TEST=${{matrix.with-tests}} -t coincenter -f ${{matrix.file-name}} .
