name: MacOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xcode:
    name: Build on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [g++-11]
        buildmode: [Debug]
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: brew install ninja

      - name: Configure
        run: cmake -S . -B build -GNinja
        env:
          CXX: ${{matrix.compiler}}
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build .

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -j 2 --output-on-failure
