name: MacOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xcode:
    name: Build on MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: brew install ninja

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-11 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl@1.1 -GNinja

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: ninja

      - name: Local Tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure --exclude-regex api_test

      - name: Public API Tests # Tries several times to avoid random timeout errors not coming from coincenter
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure --tests-regex api_test --repeat until-pass:10
