name: MacOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  xcode:
    name: Build on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [g++-13]
        buildmode: [Debug]
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          brew update && brew upgrade
          brew install ninja
          echo "CC=$(echo ${{matrix.compiler}} | sed -e 's/^g++/gcc/' | sed 's/+//g')" >> $GITHUB_ENV

      - name: Configure
        run: cmake -DCCT_ENABLE_ASAN=OFF -S . -B build -GNinja
        env:
          CXX: ${{matrix.compiler}}
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}

      - name: Build
        run: cmake --build build --config ${{matrix.buildmode}}

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -j 2 --output-on-failure --repeat until-pass:5

      - name: Sanity check main executable
        working-directory: ${{github.workspace}}/build
        run: ./coincenter --help
