name: Monitoring

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ubuntu-monitoring-build:
    name: Build on Ubuntu with monitoring support
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-11]
        buildmode: [Debug]
        build-prometheus-from-source: [0, 1]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install cmake libssl-dev git libcurl4-gnutls-dev ninja-build -y --no-install-recommends

      - name: Install prometheus-cpp
        run: |
          git clone https://github.com/jupp0r/prometheus-cpp.git
          cd prometheus-cpp
          git submodule init
          git submodule update

          mkdir _build
          cd _build

          cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PULL=OFF -DENABLE_PUSH=ON -DENABLE_COMPRESSION=OFF -DENABLE_TESTING=OFF -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -GNinja
          ninja

          sudo cmake --install .
        if: matrix.build-prometheus-from-source == 0

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCCT_BUILD_PROMETHEUS_FROM_SRC=${{matrix.build-prometheus-from-source}} -GNinja

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ninja

      - name: Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -j 4 -C ${{matrix.buildmode}} --output-on-failure