name: Special

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ubuntu-special-build:
    name: Build on Ubuntu with monitoring / protobuf support
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        buildmode: [Debug]
        build-special-from-source: [0, 1]
        prometheus-options: ["-DBUILD_SHARED_LIBS=ON -DENABLE_PULL=OFF -DENABLE_PUSH=ON -DENABLE_COMPRESSION=OFF -DENABLE_TESTING=OFF"]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt install cmake libssl-dev git libcurl4-openssl-dev ninja-build -y --no-install-recommends

      - name: Install prometheus-cpp
        run: |
          git clone https://github.com/jupp0r/prometheus-cpp.git
          cd prometheus-cpp
          git submodule init
          git submodule update

          cmake -S . -B _build -DBUILD_SHARED_LIBS=ON -DENABLE_PULL=OFF -DENABLE_PUSH=ON -DENABLE_COMPRESSION=OFF -DENABLE_TESTING=OFF -GNinja
          cmake --build _build

          sudo cmake --install _build
        env:
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}
        if: matrix.build-special-from-source == 0

      - name: Configure CMake
        run: cmake -S . -B build -DCCT_BUILD_PROMETHEUS_FROM_SRC=${{matrix.build-special-from-source}} -DCCT_ENABLE_PROTO=${{matrix.build-special-from-source}} -DCCT_ENABLE_ASAN=OFF -GNinja
        env:
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}

      - name: Build
        run: cmake --build build

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure --repeat until-pass:5

      - name: Sanity check main executable
        working-directory: ${{github.workspace}}/build
        run: ./coincenter --help
