name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-11, clang++-18]
        buildmode: [Debug, Release]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install cmake libssl-dev libcurl4-openssl-dev ninja-build -y --no-install-recommends

      - name: Install gcc
        run: |
          sudo apt install ${{matrix.compiler}} -y --no-install-recommends

          # Temporary workaround for libasan bug stated here: https://github.com/google/sanitizers/issues/1716
          sudo sysctl vm.mmap_rnd_bits=28
        if: startsWith(matrix.compiler, 'g++')

      - name: Install clang
        run: |
          CLANG_VERSION=$(echo ${{matrix.compiler}} | cut -d- -f2)
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${CLANG_VERSION}
        if: startsWith(matrix.compiler, 'clang++')

      - name: Configure CMake
        run: cmake -S . -B build -GNinja
        env:
          CXX: ${{matrix.compiler}}
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}

      - name: Build
        run: cmake --build build

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure --repeat until-pass:5

      - name: Sanity check main executable
        working-directory: ${{github.workspace}}/build
        run: ./coincenter --help