name: Clang-tidy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ubuntu-clang-tidy-build:
    name: Build on Ubuntu with clang-tidy checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clang-version: [20]
        buildmode: [Debug]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install cmake libssl-dev libcurl4-openssl-dev ninja-build -y --no-install-recommends

      - name: Install clang (with clang-tidy)
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{matrix.clang-version}}
          sudo apt install clang-tidy-${{matrix.clang-version}}
          sudo ln -s /usr/bin/clang-tidy-${{matrix.clang-version}} /usr/local/bin/clang-tidy

      - name: Configure CMake
        run: |
          clang-tidy --dump-config
          cmake -S . -B build -DCCT_ENABLE_CLANG_TIDY=ON -DCCT_ENABLE_ASAN=OFF -GNinja
        env:
          CC: clang-${{matrix.clang-version}}
          CXX: clang++-${{matrix.clang-version}}
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}

      - name: Build
        run: cmake --build build
