name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_ubuntu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-11, clang++-13]
        buildmode: [Debug, Release]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install libcurl4-gnutls-dev ninja-build

      - name: Install gcc
        run: |
          sudo apt install ${{matrix.compiler}}
        if: matrix.compiler == 'g++-11'

      - name: Install clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 13
        if: matrix.compiler == 'clang++-13'

      - name: Install clang-tidy
        run: |
          sudo apt install clang-tidy-13
          sudo ln -s /usr/bin/clang-tidy-13 /usr/bin/clang-tidy
        if: matrix.compiler == 'clang++-13' && matrix.buildmode == 'Debug'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -GNinja

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ninja

      - name: Local Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure --exclude-regex api_test

      - name: Public API Tests # Tries several times to avoid random timeout errors not coming from coincenter
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure --tests-regex api_test --repeat until-pass:10
