name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_ubuntu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-10, g++-11, clang++-13]
        buildmode: [Debug, Release]

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev libcurl4-gnutls-dev

    - name: Install compiler
      run: |
        sudo apt-get install ${{matrix.compiler}}
      if: matrix.compiler == 'g++-10' || matrix.compiler == 'g++-11'
    
    - name: Install compiler
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 13
      if: matrix.compiler == 'clang++-13'

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
   
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${{matrix.buildmode}} -j 2

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration. Print debug traces on failure
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure
