name: Monitoring

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_ubuntu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-10]
        buildmode: [Debug]
        build-prometheus-from-source: [0, 1]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Prerequisites
        run: |
          sudo apt install libssl-dev libcurl4-gnutls-dev ninja-build g++-10

      - name: Install prometheus-cpp
        run: |
          git clone https://github.com/jupp0r/prometheus-cpp.git
          cd prometheus-cpp
          git submodule init
          git submodule update

          mkdir _build
          cd _build

          cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PULL=OFF -DENABLE_PUSH=ON -DENABLE_COMPRESSION=OFF -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -GNinja
          ninja

          ctest
          sudo cmake --install .

        if: matrix.build-prometheus-from-source == 0

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}} -DCCT_BUILD_PROMETHEUS_FROM_SRC=${{matrix.build-prometheus-from-source}} -GNinja

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ninja

      - name: Local Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure --exclude-regex api_test

      - name: Public API Tests # Tries several times to avoid random timeout errors not coming from coincenter
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure --tests-regex api_test --repeat until-pass:10
