name: Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        buildmode: [Debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          vcpkg install curl

      - name: End vcpkg install
        run: |
          vcpkg integrate install

      - name: Configure CMake
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{matrix.buildmode}} -S . -B build

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{matrix.buildmode}} --parallel 4

      - name: Local Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.buildmode}} --output-on-failure --exclude-regex api_test

      - name: Public API Tests # Tries several times to avoid random timeout errors not coming from coincenter
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.buildmode}} --output-on-failure --tests-regex api_test --repeat until-pass:10
