name: Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_windows_build:
    runs-on: windows-latest
    strategy:
      matrix:
        buildmode: [Debug, Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install curl openssl

      - name: Add cURL directory in the path
        run: |
          $curlPath = Get-ChildItem -Path C:\ProgramData\chocolatey\lib\curl\tools\curl* -Name
          echo "C:\ProgramData\chocolatey\lib\curl\tools\${curlPath}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\chocolatey\lib\curl\tools\${curlPath}\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=${{matrix.buildmode}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{matrix.buildmode}} --parallel 2

      - name: Local Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.buildmode}} --output-on-failure --exclude-regex api_test

      - name: Public API Tests # Tries several times to avoid random timeout errors not coming from coincenter
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.buildmode}} --output-on-failure --tests-regex api_test --repeat until-pass:10
