name: Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        buildmode: [Debug]
        generator: [Visual Studio 17 2022]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake with vcpkg
        run: cmake -S . -B build -G "${{matrix.generator}}"
        env:
          CMAKE_BUILD_TYPE: ${{matrix.buildmode}}
          CMAKE_TOOLCHAIN_FILE: "C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --parallel 4

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -j 2 -C ${{matrix.buildmode}} --output-on-failure
