name: Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci_windows_build:
    runs-on: windows-latest
    strategy:
      matrix:
        buildmode: [Debug, Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install curl openssl

      - name: Add cURL directory in the path
        run: |
           echo "C:\ProgramData\chocolatey\lib\curl\tools\curl-7.79.0-win64-mingw\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
           echo "C:\ProgramData\chocolatey\lib\curl\tools\curl-7.79.0-win64-mingw\lib" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=${{matrix.buildmode}}

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{matrix.buildmode}} --parallel 2

      - name: Tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.buildmode}} -j 2 --output-on-failure
